Fix opentelemetry-kube-stack uninstall to remove the namespaces it creates (#393)

diff --git a/guides/kubernetes/configuration/opentelemetry-kube-stack/uninstall b/guides/kubernetes/configuration/opentelemetry-kube-stack/uninstall
--- a/guides/kubernetes/configuration/opentelemetry-kube-stack/uninstall
+++ b/guides/kubernetes/configuration/opentelemetry-kube-stack/uninstall
@@ -12,7 +12,8 @@ It deletes:
     opentelemetry-operator-system namespace;
   - the datadog-secret secret in the opentelemetry-operator-system namespace;
   - OpenTelemetry CRDs: opentelemetrycollectors, instrumentations, and
-    opampbridges.
+    opampbridges;
+  - the cert-manager and opentelemetry-operator-system namespaces.
 
 Deleting CRDs also deletes all corresponding custom resources in the cluster.
 EOF
@@ -37,7 +38,7 @@ kubectl delete crd \
 
 helm uninstall opentelemetry-kube-stack \
   --namespace opentelemetry-operator-system  \
-  || echo "WARNING: Could not uninstall opentelemetry-stack. Continuing..."
+  || echo "WARNING: Could not uninstall opentelemetry-kube-stack. Continuing..."
 
 echo "Removing Datadog endpoint configuration..."
 kubectl delete secrets --namespace opentelemetry-operator-system  --ignore-not-found=true datadog-secret
@@ -48,3 +49,6 @@ echo "Delete CRDs"
 kubectl delete crd  --namespace opentelemetry-operator-system opentelemetrycollectors.opentelemetry.io
 kubectl delete crd  --namespace opentelemetry-operator-system instrumentations.opentelemetry.io
 kubectl delete crd  --namespace opentelemetry-operator-system opampbridges.opentelemetry.io
+
+echo "Removing namespaces..."
+kubectl delete namespace --ignore-not-found=true opentelemetry-operator-system cert-manager
